
[halloween_start]
	#Day from which villagers will start placing pumpkins & trick or treating
	#Range: 1 ~ 12
	month = 10
	#Day from which villagers will start placing pumpkins & trick or treating
	#Range: 1 ~ 31
	day = 20

[halloween_end]
	#Day from which villagers will start removing placed pumpkins
	#Range: 1 ~ 12
	month = 11
	#Day from which villagers will start removing placed pumpkins
	#Range: 1 ~ 31
	day = 10

[trick_or_treating]
	#Time of day at which baby villagers will start trick-or-treating
	#Range: 0 ~ 24000
	start_time = 12000
	#Time of day at which baby villagers will stop trick-or-treating. Note that this will only properly work if it's at night since baby villagers can only trick or treat during their sleep schedule which is from 12000 to 0
	#Range: 0 ~ 24000
	end_time = 0

[serene_seasons_compat]
	#Enables Serene Seasons compatibility. Only takes effect if the mod is installed. Will make trick or treating only active during certain seasons. Note that this will override previous time window settings
	enabled = false

