
#General settings
[general]
	#Outside-of-render-distance train sync time (in ticks)
	#Range: 10 ~ 600
	farTrainUpdateTicks = 200
	#Conductor whistle is limited to the owner of a train
	mustOwnBoundTrain = false
	#In-render-distance train sync time (in ticks)
	#Range: 1 ~ 600
	nearTrainUpdateTicks = 1

#Semaphore settings
[semaphore]
	#Whether semaphore color order is reversed when the semaphores are oriented upside-down
	semaphoresFlipYellowOrder = false
	#Simplified semaphore placement
	simplifiedSemaphorePlacement = true

