
[effects]
	#If the Snow Top drinks' special effects should be used
	enableSnowTopDrinkEffects = true
	#The minimum duration requirement for an effect to be upgraded by Snow Top Green Tea / Snow Top Coffee
	#Range: > 1
	snowTopDrinkEffectMinDuration = 400
	#The maximum duration of effects transformed by Snow Top Yellow Tea / Snow Top Black Tea
	#Range: > 1
	snowTopDrinkEffectMaxDuration = 32766
	#If the drinks from Farmer's Respite can be drunk even when the player is full
	canFarmersRespiteDrinksAlwaysEat = true
	#If the foods made from tea in Farmer's Respite should use Respiteful's effects instead
	replaceFarmersRespiteFoodEffects = true
	#If the Caffeinated effect should be using the new attribute as in 1.19+
	#The new attribute would be + 10% Speed & + 20% Attack Speed per level
	#@ApiStatus.ScheduledForRemoval: this config will be removed in 1.19+ since it would be meaningless by then
	replaceCaffeinatedEffect = true

