
#configs only for clients
[Client]
	#
	#The side of the information HUD. Ex: LEFT, RIGHT
	#Allowed Values: LEFT, RIGHT
	HUDPosition = "LEFT"
	#
	#Displays the compass information HUD even while chat is open.(default:true)
	DisplayWithChatOpen = true
	#
	#The X offset for information rendered on the HUD.(default:7)
	#Range: 0 ~ 9600
	xOffset = 7
	#
	#The Y offset for information rendered on the HUD.(default:16)
	#Range: 0 ~ 5400
	yOffset = 16
	#
	#The line offset for information rendered on the HUD.(default:1)
	#Range: 0 ~ 50
	OverlayLineOffset = 1
	#
	#The X/Y/Z-distance won't be shown if it is smaller than the value.(default:0.3)
	#Range: 0.0 ~ 50.0
	CloseEnough = 0.3

